### ISSUE TITLE
Exception when running chat client

### ISSUE THREAD

**Issue by nanderh** [mothran/bunny#2]
Awesome work!!
When I run the chat client or just listen for a while it sometimes throws the following exception:

Exception in thread BunnyReadThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/root/bunny/libbunny/bunny.py", line 191, in run
    temp = type[2].decode(encoded)
  File "/root/bunny/libbunny/Templates.py", line 359, in decode
    return temp_tags[0][2]
IndexError: list index out of range

For as far as Ive been able to figure out it does not affect the usage of the client.

**Comment by mothran** [comment]
Haha, yeah there is an issue with accidentally parsing the FCS (frame check sum) as a vendor tag.  Funny enough there is a TODO above that line that mentions that exact problem.  I am currently working on overhauling the crypto system to include AES-GCM but I will get this problem patched up soon.

**Comment by mothran** [comment]
Ok I just pushed fix (I hope) for this exception.

Commit: https://github.com/mothran/bunny/commit/cfcc8d3246ad5b13aa9f7bc7cd748b422fd24510

Could you tell me if you see the problem again?  I am in a low ProbeReq WiFi eco-system so it is hard to test.
