### ISSUE TITLE
Ping pong transfer time error

### ISSUE THREAD

**Issue by nanderh** [mothran/bunny#3]
The last update fixed the chat client but it did something to the ping pong. Pings are sent and received, pong is sent but not received and when it tries to print the summary eg. packets loss etc. it trows and exception when trying to calculate the transfer time.

root@bt:~/bunnymk2/bunny# python bunnyChat.py -p
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
received:       0 packets
Percent recv'd: 0.000000%
Traceback (most recent call last):
  File "bunnyChat.py", line 246, in <module>
    main()
  File "bunnyChat.py", line 192, in main
    print "Mean time:   %f" % (avg_time / count)
ZeroDivisionError: integer division or modulo by zero

Quick fix:
in bunnyChat.py line 192, change:
print "Mean time:   %f" % (avg_time / count)
into:
if count > 0:
     print "Mean time:   %f" % (avg_time / count)

**Comment by mothran** [comment]
Turns out there was an issue with how I was parsing the new packet format.  I just added https://github.com/mothran/bunny/commit/812b7c9ab72e002387c38aad3ff142f28571cf06 and that should solve the issue.  

Thanks for letting me know, out of curiosity what hardware are you using?

**Comment by nanderh** [comment]
The netgear wnr1100 with ath9k driver on both computers. One running ubuntu
and other kali linux. Although one consideration for the documentation is
informing about the config file, because i was pulling my hair out at first
when it chose the wrong wifi adapter.

**Comment by mothran** [comment]
Hmm, I will make sure to clean that up then, it is a bit hidden.
